apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    name: tomcat
spec:
  containers:
    - name: tomcat
      image: tomcat
      ports:
        - containerPort: 8080
          name: tomcat

---

apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  type: NodePort
  ports:
    - nodePort: 31500  
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: tomcat

