apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-node1
  labels: 
    app: zookeeper-node1
spec:
  volumes:
  - name: zookeeper-disk
    persistentVolumeClaim:
      claimName: kube-disk-claim  
  containers: 
  - name: zookeeper-node1
    resources:
      requests:
        memory: 100Mi
      limits: 
        memory: 256Mi
    env:
    - name: ZOO_MY_ID
      value: "1"
    - name: ZOO_SERVERS
      value: server.1=0.0.0.0:2888:3888    
    - name: ZOO_LOG4J_PROP
      value: INFO,ROLLINGFILE
    image: "zookeeper:3.4.12"
    imagePullPolicy: Always
    ports:
    - containerPort: 2181
      name: client
    - containerPort: 2888
      name: node-contact
    - containerPort: 3888
      name: node-election
    volumeMounts:
    - mountPath: /data
      name: zookeeper-disk
      subPath: zookeeper/node1/data
    - mountPath: /datalog
      name: zookeeper-disk
      subPath: zookeeper/node1/datalog
    - mountPath: /logs
      name: zookeeper-disk
      subPath: zookeeper/logs

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-node1
spec:
  selector:
    app: zookeeper-node1
  externalIPs:
  - 10.254.0.11
  ports:
  - name: client
    port: 2181
  - name: node-contact
    port: 2888
  - name: node-election
    port: 3888




