apiVersion: apps/v1
kind: Deployment
metadata: 
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-disk
          persistentVolumeClaim:
            claimName: kube-disk-claim
      containers:
      - name: redis
        image: redis
        env:
          - name: logfile
            value: /mnt/data/redis/redis.log
          - name: dir
            value: /mnt/data/redis/data
          - name: loglevel
            value: debug
        command: ["/usr/local/bin/redis-server"]
        args: ["--logfile $(logfile)","--dir $(dir)","--loglevel $(loglevel)"]
        ports:
          - containerPort: 6379
        volumeMounts:
          - mountPath: /mnt/data/redis/data
            name: redis-disk
            subPath: redis/data
          - mountPath: /mnt/data/redis/redis.log
            name: redis-disk
            subPath: redis/redis.log

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  externalIPs:
    - 10.254.0.2

