apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-disk 
  labels:
    name: kube-disk
spec:
  storageClassName: local-kube-disk
  capacity:
    storage: 10Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/kube/pod/disk
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: kube-disk-claim
spec:
  storageClassName: local-kube-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: kube-disk


