apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-disk 
  labels:
    name: kube-disk
spec:
  storageClassName: nfs-kube-disk
  capacity:
    storage: 10Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.1.19
    path: /nfs-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: kube-disk-claim
spec:
  storageClassName: nfs-kube-disk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: kube-disk


