apiVersion: apps/v1
kind: Deployment
metadata: 
  name: zabbix-web
spec:
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      volumes:
        - name: zabbix-web
          persistentVolumeClaim:
            claimName: kube-disk-claim
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-mysql:alpine-3.4.12
          env:
            - name: DB_SERVER_HOST
              value: "10.254.0.3"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: "123456"
            - name: ZBX_SERVER_HOST
              value: "10.254.0.31"
            - name: PHP_TZ
              value: "Asia/Shanghai"

          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: zabbix-web
              subPath: zabbix-web 

---

apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
spec:
  selector:
    app: zabbix-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 10.254.0.32

