FROM centos
RUN yum -y install net-tools.x86_64 openssl openssh-server openssh-clients expect which && \
ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N '' && \    
ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '' && \
ssh-keygen -t dsa -f /etc/ssh/ssh_host_ed25519_key  -N '' && \
ssh-keygen -f /root/.ssh/id_rsa  -N '' && \ 
cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
sed -i "s/#UsePrivilegeSeparation.*/UsePrivilegeSeparation no/g" /etc/ssh/sshd_config && \
sed -i "s/UsePAM.*/UsePAM yes/g" /etc/ssh/sshd_config && \
echo "12345678" | passwd --stdin root && \
yum clean all
CMD /usr/sbin/sshd -D
EXPOSE 22 
