FROM tumingjian/centos-ssh
ENV JAVA_VERSION=8 \
    JAVA_UPDATE=112 \
    JAVA_BUILD=15 \
    JDK_HOME=/usr/lib/jdk 
ENV JAVA_HOME=${JDK_HOME}/jdk1.${JAVA_VERSION}.0_${JAVA_UPDATE}
ENV PATH=${PATH}:${JAVA_HOME}/bin
RUN  echo $PATH && \ 
yum -y install wget && \
wget --header "Cookie: oraclelicense=accept-securebackup-cookie;" "http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION}u${JAVA_UPDATE}-b${JAVA_BUILD}/jdk-${JAVA_VERSION}u${JAVA_UPDATE}-linux-x64.tar.gz" -P /tmp && \ 
mkdir -p ${JDK_HOME} && \
tar zxf /tmp/jdk-${JAVA_VERSION}u${JAVA_UPDATE}-linux-x64.tar.gz -C $JDK_HOME && \ 
yum clean all && \ 
rm -rf "$JAVA_HOME/"*src.zip && \ 
rm -rf "$JAVA_HOME/lib/missioncontrol" \
           "$JAVA_HOME/lib/visualvm" \
           "$JAVA_HOME/lib/"*javafx* \
           "$JAVA_HOME/jre/lib/plugin.jar" \
           "$JAVA_HOME/jre/lib/ext/jfxrt.jar" \
           "$JAVA_HOME/jre/bin/javaws" \
           "$JAVA_HOME/jre/lib/javaws.jar" \
           "$JAVA_HOME/jre/lib/desktop" \
           "$JAVA_HOME/jre/plugin" \
           "$JAVA_HOME/jre/lib/"deploy* \
           "$JAVA_HOME/jre/lib/"*javafx* \
           "$JAVA_HOME/jre/lib/"*jfx* \
           "$JAVA_HOME/jre/lib/amd64/libdecora_sse.so" \
           "$JAVA_HOME/jre/lib/amd64/"libprism_*.so \
           "$JAVA_HOME/jre/lib/amd64/libfxplugins.so" \
           "$JAVA_HOME/jre/lib/amd64/libglass.so" \
           "$JAVA_HOME/jre/lib/amd64/libgstreamer-lite.so" \
           "$JAVA_HOME/jre/lib/amd64/"libjavafx*.so \
           "$JAVA_HOME/jre/lib/amd64/"libjfx*.so && \ 
rm -rf /tmp
	
